apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mf3j5rti4-nodejs
  janus-idp.io/tekton: mf3j5rti4-nodejs
  backstage.io/kubernetes-id: mf3j5rti4-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: mf3j5rti4-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
